= Datawarehouse

== Mitarbeitsüberprüfung
Wird stattfinden über Datawarehouse nächstes mal, also am 18.11.2021.
Ungefähr 3 kleine Fragen.

Hier ist die PDF von dem All Laufwerk:
link:../files/datawarehouse.pdf[PDF]

== Fragen

=== Wie kann ich 2 Datenbanken verbinden/linken?

*Antwort*: database link und sql load

link:https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_5005.htm[CREATE DATABASE LINK]

=== Wie kann ich files in Datenbanken laden?

*Antwort*: sql loader

link:https://docs.oracle.com/cd/B19306_01/server.102/b14215/ldr_params.htm[SQL LOADER]


=== Wie kann ich daten kopieren nach einer bestimmten Zeit?

*Antwort*: Jobs

== Film Vorlesung Datawarehouse

=== Stern-Schema
Sind normale Tabellen nur das das Schema Stern-Schema heißt.
Es gibt 1 Faktentabelle und mehrere Dimensionstabellen.
Die Faktentabelle enthält Detaildaten.
Wie verdichtet man Tabellen?

Bei einem Select statement z.B.:

[source,sql]
```
SELECT sum(v.Anzahl)
FROM Verkäufe v, Filialen f, Produkte p, Zeit z, Kunden k
WHERE ...
GROUP BY p.Hersteller
```

schreibt man zum Schuluss ein Group By.


